config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end

  apipie
  resource :wechat, only: [:show, :create]

  root 'site#index'

  get 'site/aboutus' => 'site#about'
  get 'site/contactus' => 'site#contact'
  get 'site/privacy' => 'site#privacy'
  get 'site/career' => 'site#career'
  get 'site/faq' => 'site#faq'
  get 'site/advert'=> 'site#advert'
  get 'apps/index' => 'apps#index'
  get 'eagent/index'=>'ezhongjie#index'
  get 'site/queryreview' => 'site#queryreview'

  match 'users/sign_in' => 'users#login', via: [:get, :post]

  resources :agents do
    collection do
      post 'call'
      get 'index'
      get 'search'
      get 'asearch'
      get 'intro'
    end
    resources :comments
    resources :houses
  end
  resources :users do
    collection do
      post 'sms'
      get  'logout'
      get  'check_user'
      get  'check_mobile'
      get  'check_code'
      get  'reset'
      put  'reset'
    end
    resources :agents
  end

  resources :helper do
  end

  resources :tips do
    member do
      get 'download'
    end
    collection do
      get 'list'
    end
  end

  resources :houses do
  end

  resources :apps

  resource :orders, only: [:show, :new, :create] do
    member do
      post 'notify'
    end
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :users do
        get 'check_code', on: :collection
        get 'slides', on: :collection
      end
      resources :agents do
        post 'search', on: :collection
        get 'average', on: :collection
      end
      resources :customers do
        post 'call', on: :collection
        get 'groups', on: :collection
      end
      resources :tips do
        get 'regions', on: :collection
        get 'recommend', on: :collection
      end
      resources :comments
      resources :houses do
        get 'search', on: :collection
        get 'recommend', on: :collection
      end
    end
  end
end

app/controllers/site_controller.rb
# coding: utf-8
class SiteController < ApplicationController
  def index
    set_meta_tags title: '首页'
    set_meta_tags default_meta_tags

    agents_group_by_company = Agent.collection.aggregate([{'$group' => {'_id' => '$company', 'count' => {'$sum' => 1 }}}])
    count_summary = []
    company_summary = []
    agents_group_by_company.each do |agbc|
      if agbc[:_id].present?
        count_summary << agbc[:count]
        company_summary << agbc[:_id]
      end
    end
    @agents_data = {
      datasets: [{
                   data: count_summary,
                   backgroundColor: [
                     "#4BC0C0",
                     "#FFCE56",
                     "#FF6384",
                     "#36A2EB"
                   ],
                   label: '推荐经纪人分布'
                 }],
      labels: company_summary
    }
    @agents_options = {
      responsive: true,
      animation: {
        animateScale: true,
      }
    }

    tips_group_by_district = Tip.collection.aggregate([{'$group' => {'_id' => '$district', 'count' => {'$sum' => '$clicks'}}}])
    tips_count_summary = []
    tips_district_summary = []
    tips_group_by_district.each do |tgbc|
      if tgbc[:_id].present?
        tips_count_summary << tgbc[:count]
        tips_district_summary << tgbc[:_id]
      end
    end

    @tips_data = {
      labels: tips_district_summary,
      datasets: [
        {
          label: "锦囊下载量分布",
          backgroundColor: [
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 99, 132, 0.2)',
            'rgba(255, 206, 86, 0.2)',
          ],
          borderColor: [
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)',
            'rgba(255,99,132,1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)',
            'rgba(255,99,132,1)',
            'rgba(255, 206, 86, 1)',
          ],
          borderWidth: 1,
          data: tips_count_summary
        }
      ]
    }
    @tips_options = {
      responsive: true,
      animation: {
        animateScale: true,
      }
    }

    transactions_summary = Agent.lianjia.avg(:transactions)
    commissions_summary = Agent.lianjia.avg(:commissions)
    visits_summary = Agent.lianjia.avg(:visits)

    @summary_data = {
      datasets: [{
                   data: [transactions_summary, commissions_summary, visits_summary],
                   backgroundColor: [
                     "#FFCE56",
                     "#4BC0C0",
                     "#36A2EB"
                   ],
                   label: '经纪人关键数据'
                 }],
      labels: ['平均委托量', '平均交易量', '平均带看量']
    }
    @summary_options = {
      responsive: true,
      animation: {
        animateScale: true,
      }
    }

  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/about.html.slim
.container.site_wrapper#main-container[style="min-height:82%"]
  h4
    | 关于我们
  hr.devider
    p 我们是一家互联网房地产创业公司，致力于帮助客户找到最匹配的房屋与经纪人。
    br
    p
      span.bluefont 海量交易数据：
      | 易房好介团队称之为αHero系统。在目前千数量级的测试样本下，易房好介的αHero系统推荐满意率可达到94%。设计伊始，αHero就被定义为带有自我学习和成长的AI系统。现阶段的αHero每天可对4万条新的房产经纪人数据进行多因子线性回归分析，系统支持向量机等多个算法进行自我学习，不断修正参数以到达更好的推荐效果。CTO季善凯在国家级CAD&CG实验室有多年实践经验，目前主要负责αHero系统的数据挖掘，大数据处理，机器学习和人工智能等核心技术的构架设计。
    p
      span.bluefont 多方信息点评：
      | 易房好介技术团队与清华大学数学科学系教授合作，利用业内领先的互联网工具和方法搜集整理了全国15个大中城市近20万的房地产经纪人数据，结合平台UGC的评分和评价对其进行聚类和降维分析。利用模式识别，可靠性数据分析，语义处理，神经网络等方法从十三个维度对经纪人的工作能力，职业素养和性格品质等进行排序和推荐，致力于为租购房用户推荐最优秀的经纪人，提供最优质的租购房体验。
    br

app/views/site/advert.html.slim
.container-fluid#main-container
  .row.site_bg[style='margin-top:-20px']
    .row[style='margin-top:320px']
      .col-md-offset-3.col-md-6
        font[color='white'; face="微软雅黑"]
          center
            h1[style='text-shadow:1px 1px black'] 为您找到最优秀的经纪人
            footer[style='text-shadow:1px 1px black'] 与黑中介和假房源说再见
    .row[style='margin:24px auto 204px auto']
      .col-md-offset-3.col-md-6#search_bar
        = nav do
          = link_to '买卖','#sale',  'aria-controls':"sale", role:"tab", 'data-toggle':"tab"
          = link_to '租赁','#rent',  'aria-controls':"rent", role:"tab", 'data-toggle':"tab"
          = link_to '经纪人','#agents',  'aria-controls':"agents", role:"tab", 'data-toggle':"tab"
        .tab-content
          .tab-pane.active#sale[role='tabpanel']
            .input-group
              input.search.form-control#searchforsite[type='text' placeholder='买卖区域，商圈，小区名称' required]
              span.input-group-btn
                button.btn_search.btn.btn-success[type='button' data-loading-text='加载中...' style='background:#4bb7fc']
                  = icon :search
          .tab-pane#rent[role='tabpanel']
            .input-group
              input.search.form-control#searchforsite[type='text' placeholder='租赁区域，商圈，小区名称' required]
              span.input-group-btn
                button.btn_search.btn.btn-success[type='button' data-loading-text='加载中...' style='background:#4bb7fc']
                  = icon :search
          .tab-pane#agents[role='tabpanel']
            .input-group
              input.search.form-control#searchforsite[type='text' placeholder='经纪人姓名，手机号码' required]
              span.input-group-btn
                button.btn_search.btn.btn-success[type='button' data-loading-text='加载中...' style='background:#4bb7fc']
                  = icon :search
.container[style='']
  .row[style='margin-top:50px;padding:0 4%']
    .col-xs-12.col-md-4
      center.card_wrapper
        .row
          h4 搜索
        .row-justify.text-center.text-muted[style="line-height:12px; margin-top:12px"]
          p 告诉我们您的基本信息。
          p 地方价位、买房／卖房、求租／出租？
        .row[style='margin-bottom:12px']
          = image_tag('search.jpg', class:'img-responsive')
    .col-xs-12.col-md-4
      center.card_wrapper
        .row
          h4 匹配
        .row-justify.text-center.text-muted[style="line-height:12px; margin-top:12px"]
          p 我们有最严格的反刷单机制。
          p 大数据帮您选出最优秀，最匹配的经纪人。
        .row[style='margin-bottom:12px']
          = image_tag('match.jpg', class:'img-responsive')
    .col-xs-12.col-md-4
      center.card_wrapper
        .row
          h4 服务
        .row-justify.text-center.text-muted[style="line-height:12px; margin-top:12px"]
          p 用户使用完全免费。
          p 经纪人点评机制，让更多人享受他的服务。
        .row[style='margin-bottom:12px']
          = image_tag('service.jpg', class:'img-responsive')
.container-fluid#main-container[style='background-color:#f9f9f9;margin-top:50px;']
  .row.bg_agents
    .row
      / - if current_user.nil?
      /   .col-xs-offset-4.col-xs-4.col-md-offset-9.col-md-3[style='margin-top:12px']
      /     a.btn.btn-primary.btn-block.btn-xs[href=users_sign_in_path role='button' style='background:#4bb7fc'] 经纪人注册／登录
    .row[style='margin-top:280px']
      .col-md-offset-3.col-md-6
        font[color='white'; face="微软雅黑"]
          center
            h1[style='text-shadow:1px 1px black;marigin-top:20px;'] 为您创造更好的职业生涯
            footer[style='text-shadow:1px 1px black'] 易房好介帮你成为房地产一方豪杰
    .row[style='margin:24px auto 320px auto']
      .col-md-offset-3.col-md-6
        - if current_user.nil?
          a.btn.btn-primary.btn-block.btn-xs[href=users_sign_in_path role='button' style='background:#4bb7fc;font-size:16px;margin-top:20px;'] 
            p#login
              | 经纪人注册／登录
  .row[style='margin:24px 0; margin-left:100px;margin-right:100px;margin-top:50px;']
    .col-xs-12.col-md-3.text-center
      .card_wrapper#card1[style='background-color:#f9f9f9;margin-bottom:20px;']
        .row[style="margin-bottom:20px;"]
          = icon :star, library: :font_awesome, class: 'fa-2x'
        h4[style='color:#343434']
          | 建立威望
        p#text
          | 积攒声誉：带看房？买卖房？服务好？
        p.subheading
          | 得到客户的各方面反馈
        p.subheading2
          | 经验都是积少成多
    .col-xs-12.col-md-3.text-center
      .card_wrapper[style='background-color:#f9f9f9;margin-bottom:20px;']
        .row[style="margin-bottom:20px;"]
          = icon :user, library: :font_awesome, class: 'fa-2x'
        h4[style='color:#343434']
          | 增加客源
        p#text
          | 主动出击：还在迷茫地找客户吗？
        p.subheading
          | 建立好自己的线上简历让顾客
        p.subheading2
          | 主动找到勤快的你
    .col-xs-12.col-md-3.text-center
      .card_wrapper[style='background-color:#f9f9f9;margin-bottom:20px;']
        .row[style="margin-bottom:20px;"]
          = icon :refresh, library: :font_awesome, class: 'fa-2x'
        h4[style='color:#343434']
          | 高转换率
        p#text
          | 去伪存真： 李逵还是李贵？
        p.subheading
          | 客户有时难辨真假，不如直接
        p.subheading2
          | 找经纪人做好交易准备
    .col-xs-12.col-md-3.text-center
      .card_wrapper[style='background-color:#f9f9f9;margin-bottom:20px;']
        .row[style="margin-bottom:20px;"]
          = icon  :magnet, library: :font_awesome, class: 'fa-2x'
        h4[style='color:#343434']
          | 达成交易
        p#text
          | 以诚为本：干脆利落，顺利签约。
        p.subheading
          | 如果客户满意你的各方面服务
        p.subheading2
          | 自然会有稳定的客户源
.container[style='margin-top:10px;margin-bottom:80px;']
  .row.tips_title[style='margin-top:60px;margin-bottom:30px;']
    h2[align="center" style="font-size:36px;"] 生活锦囊
    p#[align='center' style="font-size:18px; pedding-top:15px;"] 为您寻找最舒适的生活环境 帮你探索社区 探索城市
  .row.tips_block1
    .col-md-6
      #t1
    .col-md-3
      #t2
    .col-md-3
      #t3
        #more
          = link_to "更多", list_tips_path, :style=>'color:white !important'

  .row.tips_block2[style='margin-top:30px;']
    .col-md-3
      #t4
    .col-md-3
      #t5
    .col-md-3
      #t6
    .col-md-3
      #t7
        p#w1 Beijing
        p#w2 京
.container-fluid.ubg#bg_helper[style='background: image-url("map2.jpg"); margin-top:20px;padding-bottom:200px;']
      .row.helper_title[style="margin-bottom:20px;"]
        h2[align="center" style="font-size:36px;"] 免扰电话
        p#[align='center' style="color:#696969;font-size:18px; pedding-top:15px;"] 为您提供最安心的通信方式
      .col-md-offset-4.col-md-4.wrapper#wrappernew[style="margin-top:2%;"]
        center.row.logo
          = image_tag('brand_blue_horizontal.png', size:'160x64', class:'img-responsive')
        .row[style='margin:24px auto;']
          - if session[:customer_mobile].nil?
            .alert.alert-danger[style='display:none']
            center
              .form-group
                .input-group
                  input.form-control#mobile[name='from' placeholder='我的号码' autofocus=true]
                  span.input-group-btn
                    = button context: :info, id:"btn_verify", disabled: true, data:{'loading-text':'发送中...'} do
                      | 发送验证码
            = form_for(:helper, layout: :basic, url: "/helper", remote: true) do |f|
              center
                = f.hidden_field :from, id:"from"
              center
                = f.text_field :code, use_label: false, autofocus: true, placeholder: "验证码", id:"code"
              center
                = f.text_field :to, use_label: false, placeholder: "对方号码", id:"to"
              center
                = f.submit "呼叫", class: 'btn-success btn-block', id:"btn_submit", data:{'loading-text':'呼叫中...'}
          - else
            = form_for(:helper, layout: :basic, url: "/helper", remote: true) do |f|
              center
                = f.text_field :from, use_label: false, id:"from", value:session[:customer_mobile], disabled:true
              center
                = f.text_field :to, use_label: false, placeholder: "对方号码", id:"to"
              center
                = f.submit "呼叫", class: 'btn-success btn-block', id:"btn_submit", data:{'loading-text':'呼叫中...'}
  

app/views/site/career.html.slim
.container.site_wrapper#main-container[style="min-height:82%"]
  h4
    | 加入我们
  hr.devider
    p
      | 有意者请联系。
    p
      | 技术职位申请请发邮件至
      = link_to "Shankai Ji", "mailto:jishankai@qq.com"

app/views/site/contact.html.slim
.container.site_wrapper#main-container[style="min-height:82%"]
  h4
    | 联系我们
  hr.devider
    p
      | 合作请发邮件至
      = link_to "Shankai Ji", "mailto:jishankai@qq.com"

app/views/site/faq.html.slim
.container.site_wrapper#main-container[style="min-height:82%"]
  h4
    | FAQ
  small 告别黑中介和假房源
  hr.devider
    p.bluefont Q: 什么是假房源？
    p A：互联网房源平台上存在的以诱导用户打电话为目的的虚假房源信息。主要呈现方式为：超低报价、超赞照片、“房东直租”等。某8、某居客等线上平台的竞价排名更助长了假房源的存在。

    p.bluefont Q: 为什么会有假房源？
    p A：中介想要“上客”！ 行话“上客”的意思是与客户取得联系，包括通过微信，电话，短信，站内信等方式进行销售。互联网平台上竞价排名靠前的假房源可以简单粗暴地吸引用户眼球，而真房源无人问津。一般情况下当您打电话过去咨询时，中介就会说“这套房子已经租/卖出去了，我带您看两套别的吧……”
    p.bluefont Q: 什么是黑中介？
    p A：黑中介主要可分两种:黑经纪公司与黑二房东。黑经纪公司的不规范服务包括虚假房源，乱收定金，霸王条款，扣滞押金等。黑二房东直接与用户进行租金的交易往来。除上述问题外，还包括提前赶客，乱加隔间，超级群租等安全隐患。

    p.bluefont Q：黑中介如何乱收费？
    p A：看完房立刻索要押金，入住前提前交房租，一次性收全年水电费，单收钥匙押金，不写规范押金条，退租时要求提前搬出等。一句话，只有您想不到，没有他们做不到！

    p.bluefont Q: 易房好介如何帮你告别黑中介&假房源？
    p A：易房好介用大数据帮您匹配链家，我爱我家等大公司最优秀的经纪人。因为直接向经纪人询问房源，经纪人没有办法也没有激励给假房源，将推荐给您最匹配的真房源。
      顶级经纪人的优势：大公司售后服务有保障，利益链条清晰，业务经验丰富，了解您真正的需求，更重要的是能帮您砍价（月租金一般低于官网价5%-10%，租一年就能省下中介费！）

    p.bluefont Q：我直接去找链家或我爱我家就好了，为什么需要易房好介？
    p A：大公司服务规范，但是因为行业人口流动性较大，仍存在从业人员素质参差不齐的问题。用户在实体店门户接触到的往往是刚入行的新人，服务质量难保证。易房好介综合分析带看记录、交易历史、用户评价等信息进行经纪人排名，帮你找出资深的店长级经纪人。顶级经纪人的优势在上一问里回答啦~想要最好的服务，当然需要易房好介！

    p.bluefont Q：易房好介还可以做到电话防骚扰？
    p A：是的！每个经纪公司都会有潜在用户电话号码数据库，如果您不想因为一次打电话给中介而手机号码暴露“入库”，天天被电话骚扰“要不要看房？”的话，一定记得要用易房好介的防骚扰电话功能哦！

app/views/site/privacy.html.slim
.container.site_wrapper#main-container
  h4
    | 隐私保护协议
  hr.devider
  p
    | 隐私权是用户的重要权利，对于易房好介的所有用户，我们均会以负责的态度对待您的个人信息，特此制定易房好介（http://ehero.cc，以下称"本网站"）对用户相关信息所采取的收集、使用和保护政策。易房好介隐私保护声明系本网站保护用户个人隐私的公告和承诺，请您务必仔细阅读
  p.
    | 一、用户非个人信息
  p
    | 我们将通过您的IP地址来收集非个人化的信息，例如用户的浏览器性质、操作系统种类、给您提供接入服务的ISP域名、您访问本网的顺序和链接途径、您访问时所在的地理位置等。通过收集上述信息，我们将优化在您计算机屏幕上显示的页面，同时进行客流量统计、访问者阅读习惯整理等，从而改进本网站的管理和服务。这些无关个人身份的信息能帮助我们识别易房好介最受欢迎的地区和内容等，并帮助我们确定推广活动的有效性。
  p
    | 二、用户个人信息
  p
    | 1、当您在易房好介进行用户注册登记、回答问题、发布评论等各种活动时，在您的同意并确认下，本网站将通过注册表格等形式要求您提供一些个人信息。这些个人信息包括：
  p
    | （1）个人识别资料：如姓名、性别、年龄、出生日期、身份证号码（或护照号码）、座机/手机、通信地址、住址、电子邮件地址等信息。
  p
    | （2）个人背景：职业、教育程度、收入状况、婚姻状况、家庭状况、兴趣爱好等。
  p
    | 2、请了解，在未经您同意并确认之前，本网站不会将您提供的信息用于其它目的。惟按下列第八章规定应政府及法律相关要求披露时不在此限。易房好介的目标是向所有用户提供愉快、有益的上网经历，并使每个用户使用易房好介相关服务时能够更容易、更满意，而收集这些个人信息有助于我们实现这一目标。所有的注册成员和访问者都应该知道，当他们在公告栏、聊天室或其他网上公开场合披露其个人信息时，该信息可能会被他人收集并使用，包括用来向该用户发送未经邀约的电子邮件等广告信息。
  p
    | 三、用户权利
  p
    | 1、本网站用户对于自己的个人信息享有以下权利：
  p
    | （1）随时查询及请求阅览；
  p
    | （2）随时请求补充或更正；
  p
    | （3）随时请求删除；
  p
    | （4）请求停止电脑处理及使用。
  p
    | 2、本网站为用户提供各种配套服务，如看房团、团购等各项活动，我们通常要求参与者填写相关资料登记表格，以便活动更好的开展。此类信息也将成为本网用户数据的一部分，并将被后续记录、保存、保护和合理使用。是否提供所要求的信息和是否参加此类活动，这完全取决于用户自身。
  p
    | 3、针对以上权利，本网站为您提供相关服务，如用户有任何建议或意见，请发送电子邮件至jishankai@qq.com。
  p
    | 四、用户信息安全保护
  p
    | 1、本网站将严格保护您的个人信息安全，对您所提供的信息采取严密的管理及保护措施。我们将采用相应的安全技术和程序来防止您的个人信息丢失、被盗用或遭篡改，并且保护您的个人信息不被未经授权者访问、使用或泄漏。
  p
    | 2、本网站将在必要时委托专业技术人员代为对该类资料进行电脑处理，以符合专业分工之需求。如本网站将电脑处理之通知送达予您，而您未在通知规定的时间内主动明示反对，本网站将善意推定您已同意。此后您仍然有权按照上述第三章第1条第（4）款之规定，请求停止电脑处理
  p
    | 五、用户隐私自我保护
  p
    | 1、易房好介为您提供评论、问答等服务，并善意提醒所有用户，该区域为网络公开场合，在这些区域内，您公布的任何信息都有可能成为公开的信息。因此，本网提醒您，在这些区域公开您的个人信息之前请慎重考虑。
  p
    | 2、用户是唯一对自己的账号密码及其相关注册信息负有权限及保密责任的人。因此，当你在线时，请务必小心保护自己的账户安全。
  p
    | 六、未成年人隐私权的保护
  p
    | 1、本网站将建立相应合理程序，以保护未成年人个人信息的安全。本网站郑重声明：任何十六岁以下的未成年人参加网上活动应事先得到家长或其法定监护人（以下统称为“监护人”）的明确同意。
  p
    | 2、未经监护人同意，未成年人私自上网或者冒用成人名义上网的行为将可能缺乏与未成年人相应的信息安全保护措施。
  p
    | 3、监护人应承担保护未成年人相关网络隐私的首要责任。
  p
    | 4、本网站收集未成年人的个人信息，仅为更好服务于未成人特定要求的目的，相关资料仅作为保护未成年人参与网络活动时的安全之用，而不会保留这些信息做进一步或其他商业目的的使用。
  p
    | 5、未经监护人同意，本网站将不会使用未成年人的个人信息，亦不会向任何第三方披露或传送可识别该未成人的个人信息。惟按上述第六章规定应政府及法律相关要求披露时不在此限。
  p
    | 6、若经未成年人的监护人同意，本网站可对未成年人的个人信息进行收集，本网站将向监护人提供：
  p
    | （1）审视其子女或被监护人相关信息的机会；
  p
    | （2）拒绝其子女或被监护人相关个人信息被进一步收集或使用的可能；
  p
    | （3）变更或删除其子女或被监护人个人信息。
  p
    | 7、监护人有权拒绝本网站与其子女或被监护人做进一步的联络。
  p
    | 七、用户信息使用原则惟在符合下列条件之一的情况下，本网站方可能对本网用户的个人信息进行必要范围之外的合理使用：
  p
    | 1、已取得您的书面同意；
  p
    | 2、为免除您在生命、身体或财产方面的紧急危险；
  p
    | 3、为防止他人权益的重大危害；
  p
    | 4、为增进公共利益，且无害于您的重大利益。
  p
    | 八、用户信息披露原则
  p
    | 1、根据中华人民共和国相关法律法规，当相关政府机关依照法定程序要求本网站披露相关个人信息时，本网站将根据执法单位之要求或为公共安全之目的提供相关资料。在此情况下对用户信息的任何披露，本网站均不承担任何责任。
  p
    | 2、其他易房好介因善意确信或合理原因有必要对相关用户信息进行披露的情形：
  p
    | （1）根据易房好介服务协议或易房好介其他相关声明所列的条款，有必要进行相关信息公开的；
  p
    | （2）在紧急的情况下，为保护易房好介控股公司及易房好介用户的人身或财产安全的；
  p
    | （3）为体现公平公正原则，需要对用户的部分信息进行公示的。
  p
    | 九、Cookies
  p
    | 1、Cookies是指一种技术，当使用者访问设有Cookies装置的本网站时，本网站的服务器会自动发送Cookies至用户浏览器内，并储存到其电脑硬盘内。此Cookies负责记录日后您到访本网站的种种活动、网络个人资料、浏览习惯等。
  p
    | 2、易房好介使用Cookies仅为为所有用户提供更加周到的个性化服务之目的。运用Cookies技术，本网站能够知道哪些网页或内容受欢迎。此外，本网站将会运用Cookies追访您的喜好，使您在访问我们的网站时能够得到更周密更细致的良好服务。
  p
    | 3、Cookies不会跟踪个人信息。当您注册成为我们网站会员时，易房好介会使用Cookies。在这种情况下，会存储有用信息，使您再次访问我们的网站时可辨认您的身份，从而向您提供感兴趣的信息资料或储存账号密码等，以便您造访本网站时不必每次重复登录。
  p
    | 4、来自易房好介的Cookies只能被易房好介读取。您可以选择接受或拒绝 Cookie。大多数网络浏览器会自动接受 Cookie，但您通常可根据自己的需要来修改浏览器的设置以拒绝 Cookie。如果您的浏览器被设置为拒绝Cookies，您仍然能够访问我们的大多数网页，但是您可能无法完全体验易房好介全部的网络服务或本网站的特色互动功能。
  p
    | 十、免责除上述第八章规定的免责情形外，下列情况本网站亦毋需承担任何责任：
  p
    | 1、由于您将用户密码告知他人或与他人共享注册帐户，由此导致的任何个人信息泄露，或其他非因易房好介原因导致的个人信息泄漏；
  p
    | 2、任何由于黑客政击、计算机病毒侵入或发作、因政府管制而造成的暂时性关闭等影响网络正常经营之非易房好介原因而造成的个人信息泄露、丢失、被盗用或被篡改等；
  p
    | 3、任何第三方根据易房好介各服务声明及服务协议中所列明的情况使用您的个人信息，由此所产生的纠纷；
  p
    | 4、易房好介在各服务声明及服务协议中列明的所有免责情形；
  p
    | 5、易房好介的网页上有与其他网站网页的链接。易房好介对其他任何网站的内容、隐私政策、运营情况、或经营这些网站的公司的行为概不负责。在向这些与易房好介链接的网站提供个人信息之前，请查阅它们的隐私政策。由于与本网站链接的其它网站所造成的个人信息泄露及由此而导致的任何法律争议和后果，易房好介概不负责；
  p
    | 6、任何因不可抗力所导致的后果。
  p
    | 十一、相关法律
  p
    | 本声明未涉及的问题请参见国家有关法律法规，当本声明与国家有关法律法规冲突时，以国家法律法规为准。
  p
    | 十二、本网站相关声明版权及其修改权、更新权和最终解释权均属易房好介所有。

app/views/site/queryreview.html.slim
= query_review_output