config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end

  apipie
  resource :wechat, only: [:show, :create]

  root 'site#index'

  get 'site/aboutus' => 'site#about'
  get 'site/contactus' => 'site#contact'
  get 'site/privacy' => 'site#privacy'
  get 'site/career' => 'site#career'
  get 'site/faq' => 'site#faq'
  get 'site/advert'=> 'site#advert'
  get 'apps/index' => 'apps#index'
  get 'eagent/index'=>'ezhongjie#index'
  get 'site/queryreview' => 'site#queryreview'

  match 'users/sign_in' => 'users#login', via: [:get, :post]

  resources :agents do
    collection do
      post 'call'
      get 'index'
      get 'search'
      get 'asearch'
      get 'intro'
    end
    resources :comments
    resources :houses
  end
  resources :users do
    collection do
      post 'sms'
      get  'logout'
      get  'check_user'
      get  'check_mobile'
      get  'check_code'
      get  'reset'
      put  'reset'
    end
    resources :agents
  end

  resources :helper do
  end

  resources :tips do
    member do
      get 'download'
    end
    collection do
      get 'list'
    end
  end

  resources :houses do
  end

  resources :apps

  resource :orders, only: [:show, :new, :create] do
    member do
      post 'notify'
    end
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :users do
        get 'check_code', on: :collection
        get 'slides', on: :collection
      end
      resources :agents do
        post 'search', on: :collection
        get 'average', on: :collection
      end
      resources :customers do
        post 'call', on: :collection
        get 'groups', on: :collection
      end
      resources :tips do
        get 'regions', on: :collection
        get 'recommend', on: :collection
      end
      resources :comments
      resources :houses do
        get 'search', on: :collection
        get 'recommend', on: :collection
      end
    end
  end
end

app/controllers/buttercms/authors_controller.rb
class Buttercms::AuthorsController < Buttercms::BaseController
  def show
    @author = ButterCMS::Author.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/base_controller.rb
class Buttercms::BaseController < ActionController::Base
  # You can of course change this layout to your main application layout
  # to have your blog match the rest of your site.
  layout 'buttercms/default'
end

app/controllers/buttercms/categories_controller.rb
class Buttercms::CategoriesController < Buttercms::BaseController
  def show
    @category = ButterCMS::Category.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/feeds_controller.rb
class Buttercms::FeedsController < Buttercms::BaseController
  def sitemap
    feed = ButterCMS::Feed.find(:sitemap)

    render :xml => feed.data
  end

  def atom
    feed = ButterCMS::Feed.find(:atom)

    render :xml => feed.data
  end

  def rss
    feed = ButterCMS::Feed.find(:rss)

    render :xml => feed.data
  end
end

app/controllers/buttercms/posts_controller.rb
class Buttercms::PostsController < Buttercms::BaseController
  def index
    @posts = ButterCMS::Post.all(:page => params[:page], :page_size => 10)

    @next_page = @posts.meta.next_page
    @previous_page = @posts.meta.previous_page
  end

  def show
    @post = ButterCMS::Post.find(params[:slug])

    @next_post = @post.meta.next_post
    @previous_post = @post.meta.previous_post
  end
end

app/views/buttercms/posts/_post.html.erb
<div>
  <!-- Featured image -->
  <%= image_tag(post.featured_image) if post.featured_image %>

  <!-- Post title -->
  <%= link_to post.title, buttercms_post_path(post.slug), :title => post.title %>

  <!-- Post author -->
  <%= link_to "#{post.author.first_name} #{post.author.last_name}", buttercms_author_path(post.author.slug) %>

  <!-- Post summary -->
  <%= post.summary %>

  <!-- Post categories -->
  <% post.categories.each do |category| %>
    <%= link_to category.name, buttercms_category_path(category.slug), :title => category.name %>
  <% end %>
</div>

app/views/buttercms/posts/index.html.erb
<h2>Posts</h2>

<!-- List of posts -->
<% @posts.each do |post| %>
  <%= render :partial => 'post', :locals => {:post => post} %>
<% end %>

<!-- Pagination links -->
<div>
  <% if @previous_page %>
    <%= link_to "Prev", buttercms_blog_path(:page => @previous_page) %>
  <% end %>

  <% if @next_page %>
    <%= link_to "Next", buttercms_blog_path(:page => @next_page) %>
  <% end %>
</div>

app/views/buttercms/posts/show.html.erb
<%= content_for :html_title, @post.seo_title %>
<%= content_for :meta_description, @post.meta_description %>

<!-- Post title -->
<h2><%= @post.title %></h2>

<!-- Post author -->
<%= link_to "#{@post.author.first_name} #{@post.author.last_name}", buttercms_author_path(@post.author.slug) %>

<!-- Post categories -->
<% @post.categories.each do |category| %>
  <%= link_to category.name, buttercms_category_path(category.slug), :title => category.name %>
<% end %>

<!-- Publish date -->
<%= @post.published %>

<!-- Post body -->
<%= @post.body.html_safe %>

<!-- Link to Next Post -->
<% if @next_post %>
  <%= link_to @next_post.title, buttercms_post_path(@next_post.slug), :title => @next_post.title %>
<% end %>

<!--
// For commenting, we recommend https://disqus.com/
// Create a Disqus account and paste your snippet below

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'XXXXXXXX';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
-->